import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync('./app.js','utf8');
const html=fs.readFileSync('./index.html','utf8');
const version=fs.readFileSync('./version.js','utf8');
assert.match(version,/APP_VERSION="0\.9\.25"/);
assert.match(version,/DATA_SCHEMA_VERSION=3/);
assert.match(app,/const DEFAULT_USER="HighTaxi"/);
assert.match(app,/function currentUser\(\)/);
assert.match(app,/appSettings\.chesscomUser/);
assert.match(app,/validateParsedGame\(parsed\)/);
assert.match(app,/migrateBackupGames\(rawGames/);
assert.match(app,/CHESS_SYNC_STATUS_KEY/);
assert.match(app,/saveSyncStatus\(/);
assert.match(app,/engineDiagnosticsText/);
assert.match(app,/aria-pressed/);
assert.match(html,/id="settingsAccount"/);
assert.match(html,/id="syncStatus"/);
assert.match(html,/id="engineDiagnosticsText"/);
console.log('V0.9.25 UX/ROBUSTNESS TESTS OK');
